name: Security Review
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:  # Change this from workflow_dispatch

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: anthropics/claude-code-security-review@main
        with:
          comment-pr: true  # Change to true to see results in PR
          claude-api-key: ${{ secrets.CLAUDE_API_KEY }}
