name: Manual Codebase Security Review
permissions:
  contents: read

on:
  workflow_dispatch:  # Only manual triggering

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: anthropics/claude-code-security-review@main
        with:
          comment-pr: false
          claude-api-key: ${{ secrets.CLAUDE_API_KEY }}
          upload-results: false
